package net.ethylene.server.init;

import net.ethylene.server.blocks.handlers.*;
import net.ethylene.server.blocks.placements.*;
import net.minestom.server.MinecraftServer;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockHandler;
import net.minestom.server.instance.block.rule.BlockPlacementRule;

public class Blocks {
    public static void init() {
        // Handlers
        register(new CraftingTableHandler());
        register(new FurnaceHandler());

        register(new StrippedHandler(Block.ACACIA_LOG.namespace()));
        register(new StrippedHandler(Block.OAK_LOG.namespace()));
        register(new StrippedHandler(Block.BIRCH_LOG.namespace()));
        register(new StrippedHandler(Block.CHERRY_LOG.namespace()));
        register(new StrippedHandler(Block.JUNGLE_LOG.namespace()));
        register(new StrippedHandler(Block.DARK_OAK_LOG.namespace()));
        register(new StrippedHandler(Block.MANGROVE_LOG.namespace()));
        register(new StrippedHandler(Block.SPRUCE_LOG.namespace()));

        register(new StrippedHandler(Block.ACACIA_WOOD.namespace()));
        register(new StrippedHandler(Block.OAK_WOOD.namespace()));
        register(new StrippedHandler(Block.BIRCH_WOOD.namespace()));
        register(new StrippedHandler(Block.CHERRY_WOOD.namespace()));
        register(new StrippedHandler(Block.JUNGLE_WOOD.namespace()));
        register(new StrippedHandler(Block.DARK_OAK_WOOD.namespace()));
        register(new StrippedHandler(Block.MANGROVE_WOOD.namespace()));
        register(new StrippedHandler(Block.SPRUCE_WOOD.namespace()));

        register(new TrapdoorHandler(Block.OAK_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.ACACIA_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.BAMBOO_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.BIRCH_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.CHERRY_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.CRIMSON_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.DARK_OAK_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.JUNGLE_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.MANGROVE_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.SPRUCE_TRAPDOOR.namespace()));
        register(new TrapdoorHandler(Block.WARPED_TRAPDOOR.namespace()));

        register(new GateHandler(Block.OAK_FENCE_GATE.namespace()));
        register(new GateHandler(Block.ACACIA_FENCE_GATE.namespace()));
        register(new GateHandler(Block.BAMBOO_FENCE_GATE.namespace()));
        register(new GateHandler(Block.BIRCH_FENCE_GATE.namespace()));
        register(new GateHandler(Block.CHERRY_FENCE_GATE.namespace()));
        register(new GateHandler(Block.CRIMSON_FENCE_GATE.namespace()));
        register(new GateHandler(Block.DARK_OAK_FENCE_GATE.namespace()));
        register(new GateHandler(Block.JUNGLE_FENCE_GATE.namespace()));
        register(new GateHandler(Block.MANGROVE_FENCE_GATE.namespace()));
        register(new GateHandler(Block.SPRUCE_FENCE_GATE.namespace()));
        register(new GateHandler(Block.WARPED_FENCE_GATE.namespace()));

        // Placements

        // Stairs
        register(new StairPlacementRule(Block.STONE_STAIRS));
        register(new StairPlacementRule(Block.SMOOTH_RED_SANDSTONE_STAIRS));
        register(new StairPlacementRule(Block.POLISHED_ANDESITE_STAIRS));
        register(new StairPlacementRule(Block.DEEPSLATE_BRICK_STAIRS));
        register(new StairPlacementRule(Block.SANDSTONE_STAIRS));
        register(new StairPlacementRule(Block.ANDESITE_STAIRS));
        register(new StairPlacementRule(Block.CRIMSON_STAIRS));
        register(new StairPlacementRule(Block.WAXED_OXIDIZED_CUT_COPPER_STAIRS));
        register(new StairPlacementRule(Block.END_STONE_BRICK_STAIRS));
        register(new StairPlacementRule(Block.COBBLED_DEEPSLATE_STAIRS));
        register(new StairPlacementRule(Block.PRISMARINE_BRICK_STAIRS));
        register(new StairPlacementRule(Block.QUARTZ_STAIRS));
        register(new StairPlacementRule(Block.JUNGLE_STAIRS));
        register(new StairPlacementRule(Block.POLISHED_GRANITE_STAIRS));
        register(new StairPlacementRule(Block.TUFF_STAIRS));
        register(new StairPlacementRule(Block.OAK_STAIRS));
        register(new StairPlacementRule(Block.SMOOTH_SANDSTONE_STAIRS));
        register(new StairPlacementRule(Block.SMOOTH_QUARTZ_STAIRS));
        register(new StairPlacementRule(Block.DARK_OAK_STAIRS));
        register(new StairPlacementRule(Block.COBBLESTONE_STAIRS));
        register(new StairPlacementRule(Block.MANGROVE_STAIRS));
        register(new StairPlacementRule(Block.STONE_BRICK_STAIRS));
        register(new StairPlacementRule(Block.WARPED_STAIRS));
        register(new StairPlacementRule(Block.WAXED_CUT_COPPER_STAIRS));
        register(new StairPlacementRule(Block.DIORITE_STAIRS));
        register(new StairPlacementRule(Block.PRISMARINE_STAIRS));
        register(new StairPlacementRule(Block.CHERRY_STAIRS));
        register(new StairPlacementRule(Block.TUFF_BRICK_STAIRS));
        register(new StairPlacementRule(Block.PURPUR_STAIRS));
        register(new StairPlacementRule(Block.POLISHED_TUFF_STAIRS));
        register(new StairPlacementRule(Block.RED_SANDSTONE_STAIRS));
        register(new StairPlacementRule(Block.DEEPSLATE_TILE_STAIRS));
        register(new StairPlacementRule(Block.WEATHERED_CUT_COPPER_STAIRS));
        register(new StairPlacementRule(Block.BIRCH_STAIRS));
        register(new StairPlacementRule(Block.NETHER_BRICK_STAIRS));
        register(new StairPlacementRule(Block.DARK_PRISMARINE_STAIRS));
        register(new StairPlacementRule(Block.ACACIA_STAIRS));
        register(new StairPlacementRule(Block.GRANITE_STAIRS));
        register(new StairPlacementRule(Block.WAXED_WEATHERED_CUT_COPPER_STAIRS));
        register(new StairPlacementRule(Block.BLACKSTONE_STAIRS));
        register(new StairPlacementRule(Block.RED_NETHER_BRICK_STAIRS));
        register(new StairPlacementRule(Block.BAMBOO_STAIRS));
        register(new StairPlacementRule(Block.BAMBOO_MOSAIC_STAIRS));
        register(new StairPlacementRule(Block.POLISHED_BLACKSTONE_STAIRS));
        register(new StairPlacementRule(Block.CUT_COPPER_STAIRS));
        register(new StairPlacementRule(Block.WAXED_EXPOSED_CUT_COPPER_STAIRS));
        register(new StairPlacementRule(Block.POLISHED_BLACKSTONE_BRICK_STAIRS));
        register(new StairPlacementRule(Block.POLISHED_DEEPSLATE_STAIRS));
        register(new StairPlacementRule(Block.SPRUCE_STAIRS));
        register(new StairPlacementRule(Block.OXIDIZED_CUT_COPPER_STAIRS));
        register(new StairPlacementRule(Block.MOSSY_COBBLESTONE_STAIRS));
        register(new StairPlacementRule(Block.BRICK_STAIRS));
        register(new StairPlacementRule(Block.EXPOSED_CUT_COPPER_STAIRS));
        register(new StairPlacementRule(Block.MOSSY_STONE_BRICK_STAIRS));
        register(new StairPlacementRule(Block.MUD_BRICK_STAIRS));
        register(new StairPlacementRule(Block.POLISHED_DIORITE_STAIRS));

        // Gates
        register(new GatePlacementRule(Block.OAK_FENCE_GATE));
        register(new GatePlacementRule(Block.ACACIA_FENCE_GATE));
        register(new GatePlacementRule(Block.BAMBOO_FENCE_GATE));
        register(new GatePlacementRule(Block.BIRCH_FENCE_GATE));
        register(new GatePlacementRule(Block.CHERRY_FENCE_GATE));
        register(new GatePlacementRule(Block.CRIMSON_FENCE_GATE));
        register(new GatePlacementRule(Block.DARK_OAK_FENCE_GATE));
        register(new GatePlacementRule(Block.JUNGLE_FENCE_GATE));
        register(new GatePlacementRule(Block.MANGROVE_FENCE_GATE));
        register(new GatePlacementRule(Block.SPRUCE_FENCE_GATE));
        register(new GatePlacementRule(Block.WARPED_FENCE_GATE));

        // Trapdoors
        register(new TrapdoorPlacementRule(Block.OAK_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.ACACIA_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.BAMBOO_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.BIRCH_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.CHERRY_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.CRIMSON_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.DARK_OAK_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.JUNGLE_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.MANGROVE_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.SPRUCE_TRAPDOOR));
        register(new TrapdoorPlacementRule(Block.WARPED_TRAPDOOR));

        // Horizontal (Furnace, Grazed Terracotta and Nest)
        register(new HorizontalPlacementRule(Block.GRAY_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.GREEN_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.BLACK_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.BLUE_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.BROWN_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.CYAN_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.LIGHT_BLUE_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.LIGHT_GRAY_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.LIME_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.MAGENTA_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.ORANGE_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.PINK_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.PURPLE_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.RED_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.WHITE_GLAZED_TERRACOTTA));
        register(new HorizontalPlacementRule(Block.YELLOW_GLAZED_TERRACOTTA));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.FURNACE));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.BLAST_FURNACE));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.SMOKER));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.BEEHIVE));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.BEE_NEST));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.LOOM));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.CARVED_PUMPKIN));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.JACK_O_LANTERN));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.DAMAGED_ANVIL));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.CHISELED_BOOKSHELF));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.LECTERN));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.VAULT));
        //blockManager.registerBlockPlacementRule(new HorizontalPlacementRule(Block.ENDER_CHEST));

        // Gates
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.ACACIA_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.BAMBOO_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.BIRCH_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.CHERRY_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.CRIMSON_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.DARK_OAK_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.JUNGLE_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.MANGROVE_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.OAK_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.SPRUCE_FENCE_GATE));
        //blockManager.registerBlockPlacementRule(new WaterloggedHorizontalPlacementRule(Block.WARPED_FENCE_GATE));

        // Axis (Logs, Woods, Basalt and Pillars)
        register(new FacePlacementRule(Block.OAK_LOG));
        register(new FacePlacementRule(Block.ACACIA_LOG));
        register(new FacePlacementRule(Block.OAK_LOG));
        register(new FacePlacementRule(Block.BIRCH_LOG));
        register(new FacePlacementRule(Block.CHERRY_LOG));
        register(new FacePlacementRule(Block.JUNGLE_LOG));
        register(new FacePlacementRule(Block.DARK_OAK_LOG));
        register(new FacePlacementRule(Block.MANGROVE_LOG));
        register(new FacePlacementRule(Block.SPRUCE_LOG));
        register(new FacePlacementRule(Block.WARPED_STEM));
        register(new FacePlacementRule(Block.CRIMSON_STEM));
        register(new FacePlacementRule(Block.BAMBOO_BLOCK));
        register(new FacePlacementRule(Block.STRIPPED_ACACIA_LOG));
        register(new FacePlacementRule(Block.STRIPPED_OAK_LOG));
        register(new FacePlacementRule(Block.STRIPPED_BIRCH_LOG));
        register(new FacePlacementRule(Block.STRIPPED_CHERRY_LOG));
        register(new FacePlacementRule(Block.STRIPPED_JUNGLE_LOG));
        register(new FacePlacementRule(Block.STRIPPED_DARK_OAK_LOG));
        register(new FacePlacementRule(Block.STRIPPED_MANGROVE_LOG));
        register(new FacePlacementRule(Block.STRIPPED_SPRUCE_LOG));
        register(new FacePlacementRule(Block.STRIPPED_WARPED_STEM));
        register(new FacePlacementRule(Block.STRIPPED_CRIMSON_STEM));
        register(new FacePlacementRule(Block.STRIPPED_BAMBOO_BLOCK));
        register(new FacePlacementRule(Block.ACACIA_WOOD));
        register(new FacePlacementRule(Block.OAK_WOOD));
        register(new FacePlacementRule(Block.BIRCH_WOOD));
        register(new FacePlacementRule(Block.CHERRY_WOOD));
        register(new FacePlacementRule(Block.JUNGLE_WOOD));
        register(new FacePlacementRule(Block.DARK_OAK_WOOD));
        register(new FacePlacementRule(Block.MANGROVE_WOOD));
        register(new FacePlacementRule(Block.SPRUCE_WOOD));
        register(new FacePlacementRule(Block.WARPED_HYPHAE));
        register(new FacePlacementRule(Block.CRIMSON_HYPHAE));
        register(new FacePlacementRule(Block.STRIPPED_ACACIA_WOOD));
        register(new FacePlacementRule(Block.STRIPPED_OAK_WOOD));
        register(new FacePlacementRule(Block.STRIPPED_BIRCH_WOOD));
        register(new FacePlacementRule(Block.STRIPPED_CHERRY_WOOD));
        register(new FacePlacementRule(Block.STRIPPED_JUNGLE_WOOD));
        register(new FacePlacementRule(Block.STRIPPED_DARK_OAK_WOOD));
        register(new FacePlacementRule(Block.STRIPPED_MANGROVE_WOOD));
        register(new FacePlacementRule(Block.STRIPPED_SPRUCE_WOOD));
        register(new FacePlacementRule(Block.STRIPPED_WARPED_HYPHAE));
        register(new FacePlacementRule(Block.STRIPPED_CRIMSON_HYPHAE));
        register(new FacePlacementRule(Block.POLISHED_BASALT));
        register(new FacePlacementRule(Block.BASALT));
        register(new FacePlacementRule(Block.PURPUR_PILLAR));
        register(new FacePlacementRule(Block.QUARTZ_PILLAR));
        register(new FacePlacementRule(Block.CHAIN));
        //blockManager.registerBlockPlacementRule(new AxisPlacementRule(Block.BONE_BLOCK));

        // Wall
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.DEEPSLATE_BRICK_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.POLISHED_BLACKSTONE_BRICK_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.SANDSTONE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.RED_NETHER_BRICK_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.STONE_BRICK_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.POLISHED_DEEPSLATE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.TUFF_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.POLISHED_BLACKSTONE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.MOSSY_COBBLESTONE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.DEEPSLATE_TILE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.BLACKSTONE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.DIORITE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.PRISMARINE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.END_STONE_BRICK_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.TUFF_BRICK_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.COBBLED_DEEPSLATE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.BRICK_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.GRANITE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.NETHER_BRICK_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.MOSSY_STONE_BRICK_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.COBBLESTONE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.POLISHED_TUFF_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.ANDESITE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.RED_SANDSTONE_WALL));
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.MUD_BRICK_WALL));

        // Panels
        //blockManager.registerBlockPlacementRule(new FencePlacementRule(Block.IRON_BARS));

        // Fences
        register(new FencePlacementRule(Block.ACACIA_FENCE));
        register(new FencePlacementRule(Block.CRIMSON_FENCE));
        register(new FencePlacementRule(Block.BAMBOO_FENCE));
        register(new FencePlacementRule(Block.DARK_OAK_FENCE));
        register(new FencePlacementRule(Block.BIRCH_FENCE));
        register(new FencePlacementRule(Block.OAK_FENCE));
        register(new FencePlacementRule(Block.MANGROVE_FENCE));
        register(new FencePlacementRule(Block.SPRUCE_FENCE));
        register(new FencePlacementRule(Block.JUNGLE_FENCE));
        register(new FencePlacementRule(Block.WARPED_FENCE));
        register(new FencePlacementRule(Block.CHERRY_FENCE));
        register(new FencePlacementRule(Block.NETHER_BRICK_FENCE));

        // Slabs
        register(new SlabPlacementRule(Block.POLISHED_DIORITE_SLAB));
        register(new SlabPlacementRule(Block.EXPOSED_CUT_COPPER_SLAB));
        register(new SlabPlacementRule(Block.POLISHED_TUFF_SLAB));
        register(new SlabPlacementRule(Block.WAXED_CUT_COPPER_SLAB));
        register(new SlabPlacementRule(Block.ANDESITE_SLAB));
        register(new SlabPlacementRule(Block.DARK_PRISMARINE_SLAB));
        register(new SlabPlacementRule(Block.BAMBOO_MOSAIC_SLAB));
        register(new SlabPlacementRule(Block.RED_SANDSTONE_SLAB));
        register(new SlabPlacementRule(Block.MANGROVE_SLAB));
        register(new SlabPlacementRule(Block.MUD_BRICK_SLAB));
        register(new SlabPlacementRule(Block.OAK_SLAB));
        register(new SlabPlacementRule(Block.DEEPSLATE_BRICK_SLAB));
        register(new SlabPlacementRule(Block.JUNGLE_SLAB));
        register(new SlabPlacementRule(Block.POLISHED_BLACKSTONE_BRICK_SLAB));
        register(new SlabPlacementRule(Block.CUT_COPPER_SLAB));
        register(new SlabPlacementRule(Block.POLISHED_GRANITE_SLAB));
        register(new SlabPlacementRule(Block.CRIMSON_SLAB));
        register(new SlabPlacementRule(Block.SMOOTH_RED_SANDSTONE_SLAB));
        register(new SlabPlacementRule(Block.SANDSTONE_SLAB));
        register(new SlabPlacementRule(Block.RED_NETHER_BRICK_SLAB));
        register(new SlabPlacementRule(Block.STONE_BRICK_SLAB));
        register(new SlabPlacementRule(Block.TUFF_SLAB));
        register(new SlabPlacementRule(Block.POLISHED_DEEPSLATE_SLAB));
        register(new SlabPlacementRule(Block.STONE_SLAB));
        register(new SlabPlacementRule(Block.POLISHED_ANDESITE_SLAB));
        register(new SlabPlacementRule(Block.PRISMARINE_BRICK_SLAB));
        register(new SlabPlacementRule(Block.OXIDIZED_CUT_COPPER_SLAB));
        register(new SlabPlacementRule(Block.POLISHED_BLACKSTONE_SLAB));
        register(new SlabPlacementRule(Block.WARPED_SLAB));
        register(new SlabPlacementRule(Block.MOSSY_COBBLESTONE_SLAB));
        register(new SlabPlacementRule(Block.SPRUCE_SLAB));
        register(new SlabPlacementRule(Block.DEEPSLATE_TILE_SLAB));
        register(new SlabPlacementRule(Block.BLACKSTONE_SLAB));
        register(new SlabPlacementRule(Block.ACACIA_SLAB));
        register(new SlabPlacementRule(Block.CUT_SANDSTONE_SLAB));
        register(new SlabPlacementRule(Block.SMOOTH_QUARTZ_SLAB));
        register(new SlabPlacementRule(Block.DIORITE_SLAB));
        register(new SlabPlacementRule(Block.PRISMARINE_SLAB));
        register(new SlabPlacementRule(Block.BAMBOO_SLAB));
        register(new SlabPlacementRule(Block.CUT_RED_SANDSTONE_SLAB));
        register(new SlabPlacementRule(Block.WAXED_EXPOSED_CUT_COPPER_SLAB));
        register(new SlabPlacementRule(Block.QUARTZ_SLAB));
        register(new SlabPlacementRule(Block.END_STONE_BRICK_SLAB));
        register(new SlabPlacementRule(Block.PETRIFIED_OAK_SLAB));
        register(new SlabPlacementRule(Block.TUFF_BRICK_SLAB));
        register(new SlabPlacementRule(Block.COBBLED_DEEPSLATE_SLAB));
        register(new SlabPlacementRule(Block.BRICK_SLAB));
        register(new SlabPlacementRule(Block.DARK_OAK_SLAB));
        register(new SlabPlacementRule(Block.GRANITE_SLAB));
        register(new SlabPlacementRule(Block.SMOOTH_SANDSTONE_SLAB));
        register(new SlabPlacementRule(Block.NETHER_BRICK_SLAB));
        register(new SlabPlacementRule(Block.MOSSY_STONE_BRICK_SLAB));
        register(new SlabPlacementRule(Block.BIRCH_SLAB));
        register(new SlabPlacementRule(Block.COBBLESTONE_SLAB));
        register(new SlabPlacementRule(Block.WAXED_WEATHERED_CUT_COPPER_SLAB));
        register(new SlabPlacementRule(Block.WAXED_OXIDIZED_CUT_COPPER_SLAB));
        register(new SlabPlacementRule(Block.PURPUR_SLAB));
        register(new SlabPlacementRule(Block.SMOOTH_STONE_SLAB));
        register(new SlabPlacementRule(Block.CHERRY_SLAB));
        register(new SlabPlacementRule(Block.WEATHERED_CUT_COPPER_SLAB));
    }

    private static void register(BlockHandler blockHandler) {
        MinecraftServer.getBlockManager().registerHandler(blockHandler.getNamespaceId(), () -> blockHandler);
    }

    private static void register(BlockPlacementRule blockHandler) {
        MinecraftServer.getBlockManager().registerBlockPlacementRule(blockHandler);
    }
}
